Name: **Aramina P. Galario**

Dataset: **Video Games Sales**

I chose this data set because it contains common issues such as missing values in the 'Year' and 'Publisher' columns, a 'Year' column with an inappropriate float data type, and the potential for inconsistent data formats and duplicate entries, all of which require fundamental data cleaning techniques to address.

Importing the necessary libraries

In [ ]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

Converting the .csv file to a Data Frame

In [ ]:
df = pd.read_csv("vgsales.csv")

Displaying the first 5 rows of the data set

In [ ]:
df.head()

,Rank,Name,Platform,Year,Genre,Publisher,NA_Sales,EU_Sales,JP_Sales,Other_Sales,Global_Sales
0,1,Wii Sports,Wii,2006.0,Sports,Nintendo,41.49,29.02,3.77,8.46,82.74
1,2,Super Mario Bros.,NES,1985.0,Platform,Nintendo,29.08,3.58,6.81,0.77,40.24
2,3,Mario Kart Wii,Wii,2008.0,Racing,Nintendo,15.85,12.88,3.79,3.31,35.82
3,4,Wii Sports Resort,Wii,2009.0,Sports,Nintendo,15.75,11.01,3.28,2.96,33.00
4,5,Pokemon Red/Pokemon Blue,GB,1996.0,Role-Playing,Nintendo,11.27,8.89,10.22,1.00,31.37

Checking the summary of the data frame

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 16598 entries, 0 to 16597
Data columns (total 11 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   Rank          16598 non-null  int64
 1   Name          16598 non-null  object
 2   Platform      16598 non-null  object
 3   Year          16327 non-null  float64
 4   Genre         16598 non-null  object
 5   Publisher     16540 non-null  object
 6   NA_Sales      16598 non-null  float64
 7   EU_Sales      16598 non-null  float64
 8   JP_Sales      16598 non-null  float64
 9   Other_Sales   16598 non-null  float64
 10  Global_Sales  16598 non-null  float64
dtypes: float64(6), int64(1), object(4)
memory usage: 1.4+ MB

Checking the data types

In [ ]:
df.dtypes

Rank              int64
Name             object
Platform         object
Year            float64
Genre            object
Publisher        object
NA_Sales        float64
EU_Sales        float64
JP_Sales        float64
Other_Sales     float64
Global_Sales    float64
dtype: object

Checking for missing values

In [ ]:
df.isna().sum()

Rank              0
Name              0
Platform          0
Year            271
Genre             0
Publisher        58
NA_Sales          0
EU_Sales          0
JP_Sales          0
Other_Sales       0
Global_Sales      0
dtype: int64

In [ ]:
df

,Rank,Name,Platform,Year,Genre,Publisher,NA_Sales,EU_Sales,JP_Sales,Other_Sales,Global_Sales
0,1,Wii Sports,Wii,2006.0,Sports,Nintendo,41.49,29.02,3.77,8.46,82.74
1,2,Super Mario Bros.,NES,1985.0,Platform,Nintendo,29.08,3.58,6.81,0.77,40.24
2,3,Mario Kart Wii,Wii,2008.0,Racing,Nintendo,15.85,12.88,3.79,3.31,35.82
3,4,Wii Sports Resort,Wii,2009.0,Sports,Nintendo,15.75,11.01,3.28,2.96,33.00
4,5,Pokemon Red/Pokemon Blue,GB,1996.0,Role-Playing,Nintendo,11.27,8.89,10.22,1.00,31.37
...,...,...,...,...,...,...,...,...,...,...,...
16593,16596,Woody Woodpecker in Crazy Castle 5,GBA,2002.0,Platform,Kemco,0.01,0.00,0.00,0.00,0.01
16594,16597,Men in Black II: Alien Escape,GC,2003.0,Shooter,Infogrames,0.01,0.00,0.00,0.00,0.01
16595,16598,SCORE International Baja 1000: The Official Game,PS2,2008.0,Racing,Activision,0.00,0.00,0.00,0.00,0.01
16596,16599,Know How 2,DS,2010.0,Puzzle,7G//AMES,0.00,0.01,0.00,0.00,0.01
16597,16600,Spirits & Spells,GBA,2003.0,Platform,Wanadoo,0.01,0.00,0.00,0.00,0.01

Making a new transformed dataframe containing lesser columns than the original data frame

In [ ]:
trans_df = df.drop(columns=['Year', 'NA_Sales', 'EU_Sales', 'JP_Sales', 'Other_Sales', 'Global_Sales'], axis=1)
trans_df

,Rank,Name,Platform,Genre,Publisher
0,1,Wii Sports,Wii,Sports,Nintendo
1,2,Super Mario Bros.,NES,Platform,Nintendo
2,3,Mario Kart Wii,Wii,Racing,Nintendo
3,4,Wii Sports Resort,Wii,Sports,Nintendo
4,5,Pokemon Red/Pokemon Blue,GB,Role-Playing,Nintendo
...,...,...,...,...,...
16593,16596,Woody Woodpecker in Crazy Castle 5,GBA,Platform,Kemco
16594,16597,Men in Black II: Alien Escape,GC,Shooter,Infogrames
16595,16598,SCORE International Baja 1000: The Official Game,PS2,Racing,Activision
16596,16599,Know How 2,DS,Puzzle,7G//AMES
16597,16600,Spirits & Spells,GBA,Platform,Wanadoo

Checking for any duplicated values on the new transformed data frame

In [ ]:
trans_df.duplicated().sum()

np.int64(0)

Checking for any missing values on the new transformed data frame

In [ ]:
trans_df.isna().sum()

Rank          0
Name          0
Platform      0
Genre         0
Publisher    58
dtype: int64

Showing the descriptive statistics of the data frame

In [ ]:
df.describe()

,Rank,Year,NA_Sales,EU_Sales,JP_Sales,Other_Sales,Global_Sales
count,16598.000000,16327.000000,16598.000000,16598.000000,16598.000000,16598.000000,16598.000000
mean,8300.605254,2006.406443,0.264667,0.146652,0.077782,0.048063,0.537441
std,4791.853933,5.828981,0.816683,0.505351,0.309291,0.188588,1.555028
min,1.000000,1980.000000,0.000000,0.000000,0.000000,0.000000,0.010000
25%,4151.250000,2003.000000,0.000000,0.000000,0.000000,0.000000,0.060000
50%,8300.500000,2007.000000,0.080000,0.020000,0.000000,0.010000,0.170000
75%,12449.750000,2010.000000,0.240000,0.110000,0.040000,0.040000,0.470000
max,16600.000000,2020.000000,41.490000,29.020000,10.220000,10.570000,82.740000

Dropping rows with any missing values from the "trans_df" data frame

In [ ]:
trans_df.dropna()

,Rank,Name,Platform,Genre,Publisher
0,1,Wii Sports,Wii,Sports,Nintendo
1,2,Super Mario Bros.,NES,Platform,Nintendo
2,3,Mario Kart Wii,Wii,Racing,Nintendo
3,4,Wii Sports Resort,Wii,Sports,Nintendo
4,5,Pokemon Red/Pokemon Blue,GB,Role-Playing,Nintendo
...,...,...,...,...,...
16593,16596,Woody Woodpecker in Crazy Castle 5,GBA,Platform,Kemco
16594,16597,Men in Black II: Alien Escape,GC,Shooter,Infogrames
16595,16598,SCORE International Baja 1000: The Official Game,PS2,Racing,Activision
16596,16599,Know How 2,DS,Puzzle,7G//AMES
16597,16600,Spirits & Spells,GBA,Platform,Wanadoo

Dropping rows that has missing values in the "Publisher" rows

In [ ]:
trans_df = trans_df.dropna(subset=['Publisher'])
display(trans_df)

,Rank,Name,Platform,Genre,Publisher
0,1,Wii Sports,Wii,Sports,Nintendo
1,2,Super Mario Bros.,NES,Platform,Nintendo
2,3,Mario Kart Wii,Wii,Racing,Nintendo
3,4,Wii Sports Resort,Wii,Sports,Nintendo
4,5,Pokemon Red/Pokemon Blue,GB,Role-Playing,Nintendo
...,...,...,...,...,...
16593,16596,Woody Woodpecker in Crazy Castle 5,GBA,Platform,Kemco
16594,16597,Men in Black II: Alien Escape,GC,Shooter,Infogrames
16595,16598,SCORE International Baja 1000: The Official Game,PS2,Racing,Activision
16596,16599,Know How 2,DS,Puzzle,7G//AMES
16597,16600,Spirits & Spells,GBA,Platform,Wanadoo

A final check for any missing values on the data frame

In [ ]:
trans_df.isna().sum()

Rank         0
Name         0
Platform     0
Genre        0
Publisher    0
dtype: int64